language: python
python:
- 3.6
cache: pip
install:
- pip install --upgrade pip
- pip install -r requirements.txt
script:
- make publish
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 8c136bb23ac34c67d0efc7f142273e720f4c8c35
  local_dir: output
  target_branch: gh-pages
  on:
    branch: dev
